### ISSUE TITLE
Rewriting this gbc emulator - merging it with IodineGBA

### ISSUE THREAD

**Issue by liebig** [taisel/GameBoy-Online#19]
Hi @grantgalitz,

you wrote in issue #5 that you `plan on rewriting this gbc emulator and merging it with IodineGBA in the future`. Some time has passed and I want to ask which plans do you have with GameBoy-Online? I would love to see a new release.

Thank you,
Marc

**Comment by taisel** [comment]
gameboy-online itself is gonna be the same. Any new GBC core published from me won't share its code. I've been working on GBA since I stopped working on GB/GBC, although I'll take a look back. The cores themselves won't be combined, but rather share the same exposed API, so they can be used in a separate project that interfaces with such.

Been stalling big time on GB/GBC work.
